### ISSUE TITLE
display images in a table?

### ISSUE THREAD

**Issue by tygonis** [mikelothar/show-all-images-in-a-folder-with-php#5]
Is it possible to display the images in a table? By changing the display size of the images, means you can fit more on a page, but if you have a larger selection of images, it would be more efficient to display them in a table.

**Comment by CeeJayBeenz** [comment]
Even though this issue is a year old, I would really like this for the same reason above. Bump!

**Comment by tennisfar** [comment]
You could, it's possible. You could even make a whole photo library out of this, even add a menu and more. It wasn't really my intention here though, I'd rather try to do this as simple as possible, so that it's easier to customize the layout yourself.

I can make a fork of this and go a little more into it, if you'd like.

**Comment by tennisfar** [comment]
Try this: 
https://github.com/mikelothar/show-all-images-in-a-folder-with-php/tree/flex

Demo:
http://ngu.in/show-all-images-in-a-folder-with-php-flex/
